#!/usr/bin/env python3
"""Generate the synthetic ron-closing starter documents.

A California deed-of-trust acknowledgment performed by remote online
audio-visual means on March 12, 2026 — a date on which California's Online
Notarization Act (SB 696, Stats. 2023, ch. 291) is signed law but not yet
operative. Adjudicated today the notarization is not compliant; the same
facts adjudicated at the statute's outside operative date (2030-01-01) flip.

Documents are SYNTHETIC by convention: they live in starters/ and are
generated by this committed script. It reuses the shared helpers from
starters/tools/make_documents.py (render_pdf/rendition_text/build_document)
and writes this scenario's manifest with the actual PDF SHA-256s.

Usage (from the repo root):
    uv run python starters/ron-closing/make_documents.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

STARTERS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(STARTERS / "tools"))

from make_documents import build_document  # noqa: E402

NOTARY_CERTIFICATE = [
    ("title", "NOTARY ACKNOWLEDGMENT — DEED OF TRUST"),
    ("", ""),
    ("body", "Escrow No.: ESC-4821-CA          Loan ID # L-2026-0417"),
    ("", ""),
    ("body", "State of California"),
    ("body", "County of Los Angeles"),
    ("", ""),
    ("body", "On March 12, 2026, before me, Alexis Nguyen, Notary Public, personally"),
    ("body", "appeared Rowan Delgado, who proved to me on the basis of satisfactory"),
    ("body", "evidence to be the person whose name is subscribed to the within"),
    ("body", "instrument, and acknowledged to me that they executed the same in their"),
    ("body", "authorized capacity, and that by their signature on the instrument the"),
    ("body", "person, or the entity upon behalf of which the person acted, executed"),
    ("body", "the instrument."),
    ("", ""),
    ("body", "Method of appearance: remote online notarization — the signer appeared"),
    ("body", "before the notary by two-way audio-visual communication technology and"),
    ("body", "was not in the physical presence of the notary."),
    ("", ""),
    ("body", "Notary Public: Alexis Nguyen"),
    ("body", "Commission No.: 2418807          Commission Expires: 11/30/2027"),
    ("", ""),
    ("body", "WITNESS my hand and official seal."),
    ("body", "Signature: /s/ Alexis Nguyen"),
]

CLOSING_INSTRUCTIONS = [
    ("title", "PACIFIC CREST ESCROW, INC. — CLOSING INSTRUCTIONS"),
    ("", ""),
    ("body", "Date of Instructions: March 5, 2026"),
    ("body", "Escrow No.: ESC-4821-CA          Loan ID # L-2026-0417"),
    ("body", "Borrower: Rowan Delgado"),
    ("body", "Lender: Sierra Home Lending, LLC"),
    ("body", "Property: 2716 Alder Court, Pasadena, CA 91104"),
    ("", ""),
    ("body", "Scheduled signing and closing date: March 12, 2026"),
    ("", ""),
    ("heading", "EXECUTION AND ACKNOWLEDGMENT"),
    ("body", "The Deed of Trust must be executed by the borrower and acknowledged"),
    ("body", "before a notary public prior to disbursement. The executed and"),
    ("body", "acknowledged Deed of Trust will be recorded in the Official Records of"),
    ("body", "Los Angeles County. Escrow may not close until the recorded instrument"),
    ("body", "package is complete."),
    ("", ""),
    ("body", "Return the signed instruction acknowledgment and the notarized document"),
    ("body", "package to Pacific Crest Escrow, Inc. no later than one business day"),
    ("body", "before the scheduled closing date."),
]


def main() -> None:
    cert = build_document(
        "ron-closing",
        "notary-certificate",
        NOTARY_CERTIFICATE,
        "Notary Acknowledgment ESC-4821-CA",
    )
    instructions = build_document(
        "ron-closing",
        "closing-instructions",
        CLOSING_INSTRUCTIONS,
        "Closing Instructions ESC-4821-CA",
    )

    manifest = {
        "id": "ron-closing",
        "title": "California remote online notarization eligibility for a closing",
        "caseId": "case:closing:ESC-4821-CA",
        "ontology": {"ontology": "duly-starter-ron", "version": "0.1.0"},
        "documents": [
            {
                "id": "doc:notary-certificate:ESC-4821-CA:2026-03-12",
                "title": "Notary Acknowledgment (Deed of Trust)",
                **cert,
            },
            {
                "id": "doc:closing-instructions:ESC-4821-CA:2026-03-05",
                "title": "Escrow Closing Instructions",
                **instructions,
            },
        ],
        "facts": [
            "facts/fact-cert-state.json",
            "facts/fact-cert-method.json",
            "facts/fact-instructions-closing-date.json",
        ],
        "rulePack": "rulepacks/notarization-ron-us-states/pack.yaml",
    }

    path = STARTERS / "ron-closing" / "scenario.json"
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(STARTERS.parent)}")


if __name__ == "__main__":
    main()
