#!/usr/bin/env python3
"""Regenerate spec/canonical-vectors.json.

    uv run python spec/make_canonical_vectors.py

The vectors are two things at once, and the difference matters.

As a **regression baseline** they are generated from `duly_core`, so they
cannot by themselves prove the implementation correct — a bug would be baked
into the expected output. What they pin is that the answer never *changes*
silently, which is the same job the golden corpus does for decisions.

As an **interoperability artifact** they are the thing another language needs.
Someone implementing duly's fact contract in Go or TypeScript has prose to
work from and no way to check themselves; these give them eleven exact
answers, including the two cases everyone gets wrong (UTF-16 key ordering and
raw non-ASCII output).

What actually *verifies* the definition is
`spec/tests/test_canonical_vectors.py`, which recomputes the RFC 8785
properties independently rather than trusting either this file or the
implementation. Regenerating these vectors without that test passing proves
nothing.
"""

from __future__ import annotations

import json
import pathlib

from duly_core import canonical, content_hash

OUT = pathlib.Path(__file__).resolve().parent / "canonical-vectors.json"


def vec(description: str, document: dict, hash_field: str = "contentHash") -> dict:
    body = {k: v for k, v in document.items() if k not in ("id", hash_field)}
    return {
        "description": description,
        "hashField": hash_field,
        "document": document,
        "canonical": canonical(body).decode("utf-8"),
        "sha256": content_hash(document, hash_field),
    }


VECTORS = [
    vec("empty document", {}),
    vec("keys are sorted, not written in insertion order", {"b": 1, "a": 2}),
    vec(
        "the id and hash field are excluded from the body",
        {"id": "urn:duly:fact:sha256:" + "0" * 64, "contentHash": "0" * 64, "caseId": "c1"},
    ),
    vec(
        "receipts exclude receiptSha256, not contentHash",
        {
            "id": "urn:duly:receipt:sha256:" + "0" * 64,
            "receiptSha256": "0" * 64,
            "caseId": "c1",
            "contentHash": "not-excluded-here",
        },
        "receiptSha256",
    ),
    vec("non-ASCII is emitted raw, never \\u-escaped", {"quote": "Ríos — 45 days", "caseId": "c1"}),
    vec("no whitespace anywhere", {"a": {"b": [1, 2]}, "c": "d"}),
    vec("array order is data and is preserved", {"xs": ["b", "a", "c"]}),
    vec(
        "numbers are decimal strings, never JSON floats",
        {"value": {"kind": "money", "amount": "312.40", "currency": "USD"}},
    ),
    vec("nested objects sort at every level", {"o": {"z": 1, "a": {"y": 1, "b": 2}}}),
    vec(
        "RFC 8785 sorts keys by UTF-16 code unit, not code point",
        {"\U0001f600": "emoji-non-BMP", "": "private-use-BMP"},
    ),
    vec("booleans and null survive unchanged", {"t": True, "f": False, "n": None}),
]

DOCUMENT = {
    "$comment": (
        "Canonicalization and content-addressing test vectors for duly. Any "
        "implementation, in any language, must reproduce every `canonical` string "
        "and every `sha256` exactly. See spec/grounded-facts.md D8 and "
        "core/duly_core/__init__.py. Generated by spec/make_canonical_vectors.py."
    ),
    "canonicalForm": {
        "keyOrder": "RFC 8785 (JCS): object keys sorted by UTF-16 code unit, ascending",
        "separators": "no whitespace: ',' between members, ':' between key and value",
        "stringEscaping": "JSON minimal escaping; non-ASCII emitted raw as UTF-8",
        "excludedFields": "the document's 'id' and its hash field, at the top level only",
        "encoding": "UTF-8",
        "digest": "SHA-256, lowercase hex",
    },
    "vectors": VECTORS,
}


def main() -> int:
    OUT.write_text(json.dumps(DOCUMENT, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {len(VECTORS)} vectors -> {OUT.relative_to(OUT.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
